project:
  type: website
  output-dir: docs

website:
  title: "ChemEngNuevo"
  description: "A blog construido en Quarto"
  site-url: "https://fsciolla.github.io/ChemEngNuevo/"

  navbar:
    right:
      - href: about.qmd
        text: "About"
      - icon: github
        href: "https://github.com/"
      - icon: bluesky
        href: "https://bsky.app/"

format:
  html:
    theme: 
      - cosmo
      - Brand
      - tema.scss
    css: styles.css
    toc: true